### PR TITLE
Added stop_on_assert command line option.

### PR DESCRIPTION
**Pull request by dzolee**
Added a command line option "stop_on_assert". It will cause the session to be stopped on DebugBreak() or assert().

Use case: there are some unit tests that, once asserted, end up in long loops of assertions. It is not normal that the program asserts, thus, there should be a way to stop profiling.

### CODE REVIEW

**Comment by OpenCppCoverage** [comment]
Thank you for this pull request. I am working on OpenCppCoverage plugin but once done I will working on your pull request.

**Comment by horenmar** [comment]
I am gonna add my support for a similar feature, it would be very useful for me.

**Comment by dzolee** [comment]
Hello, how are u? :) I still think this would be a cool feature here. :)

**Comment by OpenCppCoverage** [comment]
Hello,

Indeed it can be a useful feature!

I am very late on many issues in both ``OpenCppCoverage Plugin`` and ``OpenCppCoverage`` projects.
I was not active on these projects these last months. 
Now I am working again on these projects but it will require some time to handle everything. 

Thank you for the code and your patience :)

OpenCppCoverage

**Comment by dzolee** [comment]
How are u Boss?
Don't u think the tool is ready for 1.0?

**Comment by OpenCppCoverage** [comment]
Hello,

Thank again for this pull request. 

An unexpected event prevented me to work on OpenCppCoverage as I planned :(
I will create another release of OpenCppCoverage begin of 2019 (https://github.com/OpenCppCoverage/OpenCppCoverage/issues/72).

Thank for your patience!

OpenCppCoverage

**Pull request merged**
