### PR TITLE
updated jquery to the latest version (3.4.1)

### PR DESCRIPTION
**Pull request by opidopiopi**
Updated the templates to use the latest version of jquery.

### CODE REVIEW

**Comment by OpenCppCoverage** [comment]
Hi,

Updating jquery will probably not hurt, but I am wondering what this change bring? (I did not notice any visual changes). 

OpenCppCoverage

**Comment by opidopiopi** [comment]
The security team in our company sent us an alert because there are security issues with the old version. It's a routine scan of internal websites and we had to change it.

**Comment by OpenCppCoverage** [comment]
It makes sense, thank you!

OpenCppCoverage

**Comment by OpenCppCoverage** [comment]
Included in [OpenCppCoverage 0.9.9.0](https://github.com/OpenCppCoverage/OpenCppCoverage/releases/tag/release-0.9.9.0).

**Pull request merged**
